### ISSUE TITLE
Output FQ file is empty

### ISSUE THREAD

**Issue by kangxiongbin** [OmarOakheart/nPhase#20]
Hi,
I wanna to seperate my fq file by nphase. But the output folder (OUTPUT_FOLDER/Phased/FastQ/) is empty.
Do you know the reason? Many thanks!

**Comment by OmarOakheart** [comment]
Hello,

Can you tell me what version of nPhase you are running with `nphase --version` ?
If it's not 1.2.0 can you run `conda update -c oakheart nphsae` ?

If it is 1.2.0 can you send me the logfile in OUTPUT_FOLDER/Logs/* and can you tell me if there was any error in the terminal?

**Comment by kangxiongbin** [comment]
Hi,
Thanks for your reply!
Finally, I found my input data is wrong. BTW, my result FQ file (clusters) only contains small fq reads. Is it normal? I input 47 reads into nphase and it output 19 clusters which only contain 19 reads. Can I obtain the information clustering result of all reads?

**Comment by OmarOakheart** [comment]
Oh, I've never tested nPhase on so few reads. What's the coverage level for your sample? Are you just trying to phase a very small region of a genome?

I normally recommend approximately 10~15X coverage per haplotype. It's possible the coverage you're using is currently too low. It would be hard for any algorithm to decide how to phase if for example the error rate is a little too high compared to the heterozygosity rate and the coverage level is too low to compensate.

**Comment by OmarOakheart** [comment]
Marking as closed due to inactivity
