### ISSUE TITLE
Can run nPhase due to lack of matplotlib._contour

### ISSUE THREAD

**Issue by ulaszewski** [OmarOakheart/nPhase#21]
I was trying to call nPhase for the first time, but encountered this error:

_ModuleNotFoundError: No module named 'matplotlib._contour'__

How to fix this?

**Comment by rmormando** [comment]
I have the same issue when I went to run my code just now. I double checked and I have matplotlib installed and I can't find anything that helps?

My error says: `ModuleNotFoundError: No module named 'matplotlib._contour'`

**Comment by rmormando** [comment]
That seems to have done the trick! Thank you!

**Comment by ulaszewski** [comment]
It helped, thanks a lot! The pipeline is working. Is it possible to fix this issue globally (via the nPhase conda package) or have an amendment in the installtion manual?
